// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: block_list.sql

package models

import (
	"context"

	"github.com/google/uuid"
)

const getBlockedDomain = `-- name: GetBlockedDomain :one
SELECT domain, created_at FROM blocked_domain WHERE domain = $1
`

func (q *Queries) GetBlockedDomain(ctx context.Context, domain string) (BlockedDomain, error) {
	row := q.db.QueryRow(ctx, getBlockedDomain, domain)
	var i BlockedDomain
	err := row.Scan(&i.Domain, &i.CreatedAt)
	return i, err
}

const getBlockedUser = `-- name: GetBlockedUser :one
SELECT user_id, created_at FROM blocked_user WHERE user_id = $1
`

func (q *Queries) GetBlockedUser(ctx context.Context, userID uuid.UUID) (BlockedUser, error) {
	row := q.db.QueryRow(ctx, getBlockedUser, userID)
	var i BlockedUser
	err := row.Scan(&i.UserID, &i.CreatedAt)
	return i, err
}
