// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BlockedDomain struct {
	Domain    string             `json:"domain"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BlockedUser struct {
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LinkRedirect struct {
	ID           uuid.UUID          `json:"id"`
	LinkUrl      string             `json:"link_url"`
	ShortenedUrl string             `json:"shortened_url"`
	Active       bool               `json:"active"`
	Quarantined  bool               `json:"quarantined"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	UpdatedBy    uuid.UUID          `json:"updated_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Version      int32              `json:"version"`
}

type LinkRedirectHistory struct {
	ID          uuid.UUID          `json:"id"`
	LinkID      uuid.UUID          `json:"link_id"`
	LinkUrl     string             `json:"link_url"`
	Active      bool               `json:"active"`
	Quarantined bool               `json:"quarantined"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Version     int32              `json:"version"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	GivenName     *string            `json:"given_name"`
	FamilyName    *string            `json:"family_name"`
	Email         string             `json:"email"`
	EmailVerified *bool              `json:"email_verified"`
	AvatarUrl     *string            `json:"avatar_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Version       int32              `json:"version"`
}

type UserAuth struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Value        string             `json:"value"`
	Provider     string             `json:"provider"`
	ProviderID   string             `json:"provider_id"`
	ProviderData []byte             `json:"provider_data"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Version      int32              `json:"version"`
}

type UserSession struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	ImpersonatorID *uuid.UUID         `json:"impersonator_id"`
	Token          string             `json:"token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UserExpired    bool               `json:"user_expired"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Version        int32              `json:"version"`
}
